# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- powershell: |
        Invoke-WebRequest -Uri https://github.com/adoptium/temurin15-binaries/releases/download/jdk-15.0.8+7/OpenJDK15U-jdk_x64_windows_hotspot_15.0.8_7.zip -OutFile jdk15.zip
            Expand-Archive jdk15.zip -DestinationPath $(Agent.TempDirectory)\jdk15
                echo "##vso[task.setvariable variable=JAVA_HOME]$(Agent.TempDirectory)\jdk15\jdk-15.0.8+7"
                    echo "##vso[task.prependpath]$(JAVA_HOME)\bin"
                      displayName: 'Install JDK 15'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '15'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: PKHeX.Mobile'
  inputs:
    pathtoPublish: '$(outputDirectory)'
    ArtifactName: PKHeX.Android
  condition: succeededOrFailed()
